### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by serverok** [session-foundation/session-push-notification-server#4]
When starting i get the following error

```
push@vps-5b6fc469:~/session-push-notification-server$ /usr/bin/python3 -mspns.hivemind
2023-11-20 16:08:04,498 vps-5b6fc469 spns[119704] INFO Loading config from spns.ini
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Loaded hivemind X25519 keypair with pubkey f4af2b5774e482701fb4a3703cb8f67006b0b36cb18c58c34fbe10799c189cb2
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Loaded onionreq X25519 keypair with pubkey d896bc1250e2244178a92edbc85dd2ca6d1277d5e954dc958d104cc9011a4370
2023-11-20 16:08:04 vps-5b6fc469 spns[119704] INFO Starting hivemind
[2023-11-20 16:08:04] [+0.089s] [pg:info|spns/pg.cpp:12] Connecting to postgresql database @ postgresql:///spns
[2023-11-20 16:08:04] [+0.094s] [utils:warning|spns/utils.cpp:67] NOFILE limit is only 1024; increasing to 10000
[2023-11-20 16:08:04] [+0.094s] [hivemind:info|spns/hivemind.cpp:102] Listening for local connections on ipc://./hivemind.sock
terminate called without an active exception
Aborted (core dumped)
push@vps-5b6fc469:~/session-push-notification-server$ 
```

When running service

```
root@vps-5b6fc469:/home/ubuntu# systemctl start spns-hivemind
Job for spns-hivemind.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status spns-hivemind.service" and "journalctl -xeu spns-hivemind.service" for details.
root@vps-5b6fc469:/home/ubuntu# systemctl status spns-hivemind.service
● spns-hivemind.service - Session Push Notification Server -- central push handler (hivemind)
     Loaded: loaded (/etc/systemd/system/spns-hivemind.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Mon 2023-11-20 16:10:02 UTC; 2s ago
    Process: 119952 ExecStart=/usr/bin/python3 -mspns.hivemind (code=dumped, signal=ABRT)
   Main PID: 119952 (code=dumped, signal=ABRT)
     Status: "Cleaning database"
        CPU: 145ms

Nov 20 16:10:02 vps-5b6fc469 systemd[1]: spns-hivemind.service: Main process exited, code=dumped, status=6/ABRT
Nov 20 16:10:02 vps-5b6fc469 systemd[1]: spns-hivemind.service: Failed with result 'core-dump'.
Nov 20 16:10:02 vps-5b6fc469 systemd[1]: Failed to start Session Push Notification Server -- central push handler (hivemind).
root@vps-5b6fc469:/home/ubuntu# 
```

Any idea how to fix this?

**Comment by jagerman** [comment]
I'd probably need a stack trace (`coredumpctl gdb`, from the `systemd-coredump` package) to get an idea of what's going on here.

**Comment by serverok** [comment]
Thanks, i got this

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.10...
(No debugging symbols found in /usr/bin/python3.10)
[New LWP 137171]
[New LWP 137175]
[New LWP 137174]
[New LWP 137173]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python3 -mspns.hivemind'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f463fe77000 (LWP 137171))]
(gdb) 
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:44
oxen-io/session-push-notification-server#1  __pthread_kill_internal (signo=6, threadid=139939696570368) at ./nptl/pthread_kill.c:78
oxen-io/session-push-notification-server#2  __GI___pthread_kill (threadid=139939696570368, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
oxen-io/session-push-notification-server#3  0x00007f463feba476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
oxen-io/session-push-notification-server#4  0x00007f463fea07f3 in __GI_abort () at ./stdlib/abort.c:79
oxen-io/session-push-notification-server#5  0x00007f463f15cb9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
oxen-io/session-push-notification-server#6  0x00007f463f16820c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
oxen-io/session-push-notification-server#7  0x00007f463f168277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
oxen-io/session-push-notification-server#8  0x00007f463f6cb1db in spns::HiveMind::HiveMind(spns::Config) () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
oxen-io/session-push-notification-server#9  0x00007f463f76206b in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
oxen-io/session-push-notification-server#10 0x00007f463f6c2b52 in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
oxen-io/session-push-notification-server#11 0x00007f463f6ae78b in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
oxen-io/session-push-notification-server#12 0x000055be25103e0e in ?? ()
oxen-io/session-push-notification-server#13 0x000055be250fa5eb in _PyObject_MakeTpCall ()
oxen-io/session-push-notification-server#14 0x000055be25112910 in ?? ()
oxen-io/session-push-notification-server#15 0x000055be2510ed67 in ?? ()
oxen-io/session-push-notification-server#16 0x000055be250fa98b in ?? ()
oxen-io/session-push-notification-server#17 0x00007f463f6b0e5d in ?? () from /home/push/session-push-notification-server/spns/core.cpython-310-x86_64-linux-gnu.so
#18 0x000055be250fa5eb in _PyObject_MakeTpCall ()
oxen-io/session-push-notification-server#19 0x000055be250f2c66 in _PyEval_EvalFrameDefault ()
oxen-io/session-push-notification-server#20 0x000055be2510470c in _PyFunction_Vectorcall ()
oxen-io/session-push-notification-server#21 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
oxen-io/session-push-notification-server#22 0x000055be251dde56 in ?? ()
oxen-io/session-push-notification-server#23 0x000055be251ddcf6 in PyEval_EvalCode ()
oxen-io/session-push-notification-server#24 0x000055be251e3b0d in ?? ()
oxen-io/session-push-notification-server#25 0x000055be25104969 in ?? ()
oxen-io/session-push-notification-server#26 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
oxen-io/session-push-notification-server#27 0x000055be2510470c in _PyFunction_Vectorcall ()
#28 0x000055be250ece0d in _PyEval_EvalFrameDefault ()
oxen-io/session-push-notification-server#29 0x000055be2510470c in _PyFunction_Vectorcall ()
oxen-io/session-push-notification-server#30 0x000055be251fb5dd in ?? ()
oxen-io/session-push-notification-server#31 0x000055be251fa288 in Py_RunMain ()
oxen-io/session-push-notification-server#32 0x000055be251d0cad in Py_BytesMain ()
oxen-io/session-push-notification-server#33 0x00007f463fea1d90 in __libc_start_call_main (main=main@entry=0x55be251d0c70, argc=argc@entry=2, argv=argv@entry=0x7ffda30904f8) at ../sysdeps/nptl/libc_start_call_main.h:58
oxen-io/session-push-notification-server#34 0x00007f463fea1e40 in __libc_start_main_impl (main=0x55be251d0c70, argc=2, argv=0x7ffda30904f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffda30904e8)
    at ../csu/libc-start.c:392
oxen-io/session-push-notification-server#35 0x000055be251d0ba5 in _start ()
(gdb) 
```

**Comment by noobinandroid** [comment]
Any luck with this? Getting same error, running ubuntu 22

**Comment by noobinandroid** [comment]
> I'd probably need a stack trace (`coredumpctl gdb`, from the `systemd-coredump` package) to get an idea of what's going on here.

Are there any fixes on this ?

**Comment by S-U-garhish** [comment]
Same error. Dependencies is correct?

**Comment by S-U-garhish** [comment]
My environment.
Ubuntu22.04
Python3.10
cmake 3.22.1

I can provide other information. Thank you.

**Comment by S-U-garhish** [comment]
In wsl-Ubuntu24.04. (This is developping environment. Production is pure Ubuntu.)

A little bit different, however, mostly same......
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python3 -mspns.hivemind'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44

warning: 44     ./nptl/pthread_kill.c: No such file or directory
[Current thread is 1 (Thread 0x7e0774b0e080 (LWP 12627))]
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007e077484527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007e07748288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007e0773ea5ff5 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007e0773ebb0da in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007e0773ea5a55 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007e07744ec28e in spns::HiveMind::HiveMind(spns::Config) ()
   from /home/user/session-push-notification-server/spns/core.cpython-312-x86_64-linux-gnu.so
#9  0x00007e077453c65d in ?? ()
   from /home/user/session-push-notification-server/spns/core.cpython-312-x86_64-linux-gnu.so
#10 0x00007e07744e0b38 in ?? ()
   from /home/user/session-push-notification-server/spns/core.cpython-312-x86_64-linux-gnu.so
#11 0x00007e07744d21bd in ?? ()
   from /home/user/session-push-notification-server/spns/core.cpython-312-x86_64-linux-gnu.so
#12 0x000000000058208f in ?? ()
#13 0x0000000000549185 in _PyObject_MakeTpCall ()
#14 0x000000000054cea7 in ?? ()
#15 0x000000000059e231 in ?? ()
#16 0x0000000000599b63 in ?? ()
#17 0x00007e07744d0015 in ?? ()
   from /home/user/session-push-notification-server/spns/core.cpython-312-x86_64-linux-gnu.so
#18 0x0000000000549185 in _PyObject_MakeTpCall ()
#19 0x00000000005d73c9 in _PyEval_EvalFrameDefault ()
#20 0x00000000005d58eb in PyEval_EvalCode ()
#21 0x00000000005d347c in ?? ()
#22 0x0000000000581f0d in ?? ()
#23 0x0000000000549b85 in PyObject_Vectorcall ()
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00000000005d73c9 in _PyEval_EvalFrameDefault ()
#25 0x00000000006bcce2 in ?? ()
#26 0x00000000006bc912 in Py_RunMain ()
#27 0x00000000006bc57d in Py_BytesMain ()
#28 0x00007e077482a1ca in __libc_start_call_main (main=main@entry=0x5189b0, argc=argc@entry=2,
    argv=argv@entry=0x7ffcc50ef1a8) at ../sysdeps/nptl/libc_start_call_main.h:58
#29 0x00007e077482a28b in __libc_start_main_impl (main=0x5189b0, argc=2, argv=0x7ffcc50ef1a8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcc50ef198) at ../csu/libc-start.c:360
#30 0x0000000000657ce5 in _start ()
(gdb)
```
